services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    command: fastapi dev --host 0.0.0.0 --port ${APPLICATION_PORT}
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    networks:
      - fido-net
    environment:
      - DATABASE_SERVER=db
      - REDIS_HOST=redis

  db:
    build:
      dockerfile: Dockerfile
      context: ./db
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - fido-net
  
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server
    volumes:
      - fido-cache:/data
    networks:
      - fido-net
    

networks:
 fido-net:

volumes:
  fido-data:

  fido-cache: